[package]
authors = ["Łukasz Jan Niemier <lukasz@niemier.pl>"]
description = "Static ring buffer with paddings"
license = "MIT"
repository = "https://github.com/libOctavo/static-buffer.git"
name = "static-buffer"
version = "0.2.0"

[dependencies]
generic-array = "0.2.0"
typenum = "1.2.0"
